# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b185bf7723d8b2692ae2f8bfe4025f3885b9f92f2656d7aa5e3f04c8a9e580bb8e51e1805dea6ad8e628d3e1880cadc4b7e0fbdf52bddc02fc6bd2090b229b6

test:
  secret_key_base: eafcce190ca0b46bd036ceab293c0cd718f00dad6691c62ebb3ee8b6812366b149b3cab7b3e5aa1a33f4b9b7940eed928a1ce823e6735fe753b57c98d49f314e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
